source 'https://rubygems.org'

group :web do
  gem 'sinatra'
  gem 'sinatra-contrib'
  gem 'sinatra-cross_origin', '~> 0.3.1'
  gem 'thin'
  gem 'sass'
  gem 'haml'
  gem 'json'
  gem 'nokogiri'
  gem 'mysql2', '~> 0.4.4'
  gem 'pg'
  gem 'pry-byebug'
  gem 'unicorn'
  gem 'redis'
  gem 'unicode'
  gem 'httparty'
  gem 'mediawiki-gateway', github: 'MusikAnimal/mediawiki-gateway', branch: 'master'
end
